server:
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://iam.xpanse.site/oauth/v2/introspect
          client-id: 221665786966638595@eclipse-xpanse
          client-secret: 2S7yZR4jWauyE3wLHM1h5asc0WNWdBUXAw2Ill3Pmu0qM4D3LWBCwikXbsG81ycl
logging:
  level:
    root: info
    demo: debug
    org:
      springframework:
        web: info
        security: debug


springdoc:
  show-login-endpoint: true
  swagger-ui:
    oauth:
      clientId: 221664356859969539@eclipse-xpanse
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: https://iam.xpanse.site/oauth/v2/authorize
    tokenUrl: https://iam.xpanse.site/oauth/v2/token